FROM python:3.12-slim

WORKDIR /app

# Copy entire project
COPY . .

# Install dependencies from Helper
RUN pip install --no-cache-dir -r Helper/requirements.txt

# Run Helper bot
CMD ["python", "Helper/main.py"]

